FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Render uses dynamic PORT
CMD /bin/sh -c "sed -i 's/listen 80;/listen $PORT;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
