sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
        traces_sample_rate: 0.1
        profiles_sample_rate: 0.1
    tracing:
        enabled: true
        dbal:
            enabled: true
        twig:
            enabled: true
