server {
    listen 80;
    server_name localhost;

    # Frontend (React)
    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API (Symfony)
    location /api {
        fastcgi_pass backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        
        # When using fastcgi_pass, SCRIPT_FILENAME must point to the path INSIDE the backend container
        fastcgi_param SCRIPT_FILENAME /var/www/symfony/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/symfony/public;
        
        # Important for Symfony to know the path
        fastcgi_param REQUEST_URI $request_uri;
    }
    
    location /bundles {
        alias /var/www/symfony/public/bundles;
    }

    # AI Service (Python FastAPI)
    location /ai {
        rewrite ^/ai/(.*) /$1 break;
        proxy_pass http://ai_service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


