<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260122_Indexes extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds performance indexes for Student, Enrollment, GradeRecord, Payment, and AuditLog';
    }

    public function up(Schema $schema): void
    {
        // Student lookups
        $this->addSql('CREATE INDEX idx_student_active ON student(is_active) WHERE is_active = true');
        // $this->addSql('CREATE INDEX idx_student_family ON student(family_id)'); // Removed: Column does not exist yet

        // Enrollment queries
        $this->addSql('CREATE INDEX idx_enrollment_student_cycle ON enrollment(student_id, school_cycle_id)');
        $this->addSql('CREATE INDEX idx_enrollment_grade_section ON enrollment(grade_id, section_id)');

        // Grade records (highly accessed)
        // $this->addSql('CREATE INDEX idx_grade_record_lookup ON grade_record(student_id, bimester_id, subject_id)'); // Removed: Column does not exist
        $this->addSql('CREATE INDEX idx_grade_record_teacher ON grade_record(entered_by_id, created_at DESC)');

        // Payments
        $this->addSql('CREATE INDEX idx_payment_status_date ON payment(status, due_date)');
        $this->addSql('CREATE INDEX idx_payment_student_pending ON payment(student_id, status) WHERE status = \'PENDING\'');

        // Audit log (generic table)
        // Creating if not exists to avoid errors on fresh installs
        $this->addSql('CREATE TABLE IF NOT EXISTS audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id INT NOT NULL, action VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_audit_log_entity ON audit_log(entity_type, entity_id, created_at DESC)');
        $this->addSql('CREATE INDEX idx_audit_log_user ON audit_log(user_id, created_at DESC)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_student_active');
        $this->addSql('DROP INDEX idx_student_family');
        $this->addSql('DROP INDEX idx_enrollment_student_cycle');
        $this->addSql('DROP INDEX idx_enrollment_grade_section');
        $this->addSql('DROP INDEX idx_grade_record_lookup');
        $this->addSql('DROP INDEX idx_grade_record_teacher');
        $this->addSql('DROP INDEX idx_payment_status_date');
        $this->addSql('DROP INDEX idx_payment_student_pending');
        $this->addSql('DROP INDEX idx_audit_log_entity');
        $this->addSql('DROP INDEX idx_audit_log_user');
    }
}
