<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114030500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classroom (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, capacity INT NOT NULL, features JSON NOT NULL, location VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE schedule_constraint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, parameters JSON NOT NULL, severity VARCHAR(20) NOT NULL, weight INT NOT NULL, school_cycle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6980F9B0FBAA2526 ON schedule_constraint (school_cycle_id)');
        $this->addSql('CREATE TABLE teacher_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A968568D41807E1D ON teacher_availability (teacher_id)');
        $this->addSql('ALTER TABLE schedule_constraint ADD CONSTRAINT FK_6980F9B0FBAA2526 FOREIGN KEY (school_cycle_id) REFERENCES school_cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher_availability ADD CONSTRAINT FK_A968568D41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ALTER two_factor_auth_enabled DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE schedule_constraint DROP CONSTRAINT FK_6980F9B0FBAA2526');
        $this->addSql('ALTER TABLE teacher_availability DROP CONSTRAINT FK_A968568D41807E1D');
        $this->addSql('DROP TABLE classroom');
        $this->addSql('DROP TABLE schedule_constraint');
        $this->addSql('DROP TABLE teacher_availability');
        $this->addSql('ALTER TABLE "user" ALTER two_factor_auth_enabled SET DEFAULT false');
    }
}
