<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122035930 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE job_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, department VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT fk_5a3811fb591cc992');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT fk_5a3811fbfbaa2526');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT fk_5a3811fb41807e1d');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT fk_5a3811fb23edc87');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT fk_5a3811fbd823e37a');
        $this->addSql('ALTER TABLE schedule_constraint DROP CONSTRAINT fk_6980f9b0fbaa2526');
        $this->addSql('ALTER TABLE teacher_availability DROP CONSTRAINT fk_a968568d41807e1d');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE schedule_constraint');
        $this->addSql('DROP TABLE teacher_availability');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d91a40bc2d5');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d91b03a8386');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d913f3d70ea');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d9141807e1d');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d9123edc87');
        $this->addSql('DROP INDEX idx_6de30d91a40bc2d5');
        $this->addSql('DROP INDEX idx_6de30d9123edc87');
        $this->addSql('DROP INDEX idx_6de30d9141807e1d');
        $this->addSql('DROP INDEX idx_6de30d913f3d70ea');
        $this->addSql('DROP INDEX idx_6de30d91b03a8386');
        $this->addSql('DROP INDEX unique_student_schedule_date');
        $this->addSql('ALTER TABLE attendance ADD subject_assignment_id INT NOT NULL');
        $this->addSql('ALTER TABLE attendance DROP schedule_id');
        $this->addSql('ALTER TABLE attendance DROP subject_id');
        $this->addSql('ALTER TABLE attendance DROP teacher_id');
        $this->addSql('ALTER TABLE attendance DROP bimester_id');
        $this->addSql('ALTER TABLE attendance DROP created_by_id');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91A87321B1 FOREIGN KEY (subject_assignment_id) REFERENCES subject_assignment (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6DE30D91A87321B1 ON attendance (subject_assignment_id)');
        $this->addSql('ALTER TABLE grade ADD sort_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD ip_address VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP billing_identifier');
        $this->addSql('ALTER TABLE payment DROP billing_name');
        $this->addSql('ALTER TABLE staff ADD job_title_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE staff ADD CONSTRAINT FK_426EF3926DD822C6 FOREIGN KEY (job_title_id) REFERENCES job_title (id)');
        $this->addSql('CREATE INDEX IDX_426EF3926DD822C6 ON staff (job_title_id)');
        $this->addSql('ALTER TABLE student ADD version INT DEFAULT 1 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, period INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, classroom VARCHAR(50) DEFAULT NULL, is_active BOOLEAN NOT NULL, teacher_id INT NOT NULL, subject_id INT NOT NULL, course_id INT NOT NULL, section_id INT DEFAULT NULL, school_cycle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5a3811fb41807e1d ON schedule (teacher_id)');
        $this->addSql('CREATE INDEX idx_5a3811fb23edc87 ON schedule (subject_id)');
        $this->addSql('CREATE INDEX idx_5a3811fbd823e37a ON schedule (section_id)');
        $this->addSql('CREATE INDEX idx_5a3811fbfbaa2526 ON schedule (school_cycle_id)');
        $this->addSql('CREATE INDEX idx_5a3811fb591cc992 ON schedule (course_id)');
        $this->addSql('CREATE TABLE schedule_constraint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, parameters JSON NOT NULL, severity VARCHAR(20) NOT NULL, weight INT NOT NULL, school_cycle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6980f9b0fbaa2526 ON schedule_constraint (school_cycle_id)');
        $this->addSql('CREATE TABLE teacher_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a968568d41807e1d ON teacher_availability (teacher_id)');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_5a3811fb591cc992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_5a3811fbfbaa2526 FOREIGN KEY (school_cycle_id) REFERENCES school_cycle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_5a3811fb41807e1d FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_5a3811fb23edc87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_5a3811fbd823e37a FOREIGN KEY (section_id) REFERENCES section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule_constraint ADD CONSTRAINT fk_6980f9b0fbaa2526 FOREIGN KEY (school_cycle_id) REFERENCES school_cycle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_availability ADD CONSTRAINT fk_a968568d41807e1d FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE job_title');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91A87321B1');
        $this->addSql('DROP INDEX IDX_6DE30D91A87321B1');
        $this->addSql('ALTER TABLE attendance ADD schedule_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD subject_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD teacher_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD bimester_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance DROP subject_assignment_id');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d91a40bc2d5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d91b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d913f3d70ea FOREIGN KEY (bimester_id) REFERENCES bimester (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d9141807e1d FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d9123edc87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_6de30d91a40bc2d5 ON attendance (schedule_id)');
        $this->addSql('CREATE INDEX idx_6de30d9123edc87 ON attendance (subject_id)');
        $this->addSql('CREATE INDEX idx_6de30d9141807e1d ON attendance (teacher_id)');
        $this->addSql('CREATE INDEX idx_6de30d913f3d70ea ON attendance (bimester_id)');
        $this->addSql('CREATE INDEX idx_6de30d91b03a8386 ON attendance (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_student_schedule_date ON attendance (student_id, schedule_id, date)');
        $this->addSql('ALTER TABLE grade DROP sort_order');
        $this->addSql('ALTER TABLE payment ADD billing_identifier VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD billing_name VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP ip_address');
        $this->addSql('ALTER TABLE staff DROP CONSTRAINT FK_426EF3926DD822C6');
        $this->addSql('DROP INDEX IDX_426EF3926DD822C6');
        $this->addSql('ALTER TABLE staff DROP job_title_id');
        $this->addSql('ALTER TABLE student DROP version');
    }
}
