<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127200001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, link VARCHAR(500) DEFAULT NULL, subject_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC91F41641807E1D ON resource (teacher_id)');
        $this->addSql('CREATE TABLE schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, classroom VARCHAR(20) DEFAULT NULL, school_cycle_id INT DEFAULT NULL, subject_id INT NOT NULL, teacher_id INT NOT NULL, grade_id INT NOT NULL, section_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A3811FB23EDC87 ON schedule (subject_id)');
        $this->addSql('CREATE INDEX IDX_5A3811FB41807E1D ON schedule (teacher_id)');
        $this->addSql('CREATE INDEX IDX_5A3811FBFE19A1A8 ON schedule (grade_id)');
        $this->addSql('CREATE INDEX IDX_5A3811FBD823E37A ON schedule (section_id)');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F41641807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBFE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBD823E37A FOREIGN KEY (section_id) REFERENCES section (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD ip_address VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP billing_identifier');
        $this->addSql('ALTER TABLE payment DROP billing_name');
        $this->addSql('ALTER TABLE student ADD version INT DEFAULT 1 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resource DROP CONSTRAINT FK_BC91F41641807E1D');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB23EDC87');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB41807E1D');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FBFE19A1A8');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FBD823E37A');
        $this->addSql('DROP TABLE resource');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('ALTER TABLE payment ADD billing_identifier VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD billing_name VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP ip_address');
        $this->addSql('ALTER TABLE student DROP version');
    }
}
