<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126234414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE schedule_constraint');
        $this->addSql('DROP TABLE teacher_availability');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d913f3d70ea');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d91b03a8386');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d91a40bc2d5');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d9123edc87');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT fk_6de30d9141807e1d');
        $this->addSql('DROP INDEX idx_6de30d91b03a8386');
        $this->addSql('DROP INDEX idx_6de30d9141807e1d');
        $this->addSql('DROP INDEX idx_6de30d9123edc87');
        $this->addSql('DROP INDEX idx_6de30d91a40bc2d5');
        $this->addSql('DROP INDEX unique_student_schedule_date');
        $this->addSql('DROP INDEX idx_6de30d913f3d70ea');
        $this->addSql('ALTER TABLE attendance ADD subject_assignment_id INT NOT NULL');
        $this->addSql('ALTER TABLE attendance DROP schedule_id');
        $this->addSql('ALTER TABLE attendance DROP subject_id');
        $this->addSql('ALTER TABLE attendance DROP teacher_id');
        $this->addSql('ALTER TABLE attendance DROP bimester_id');
        $this->addSql('ALTER TABLE attendance DROP created_by_id');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91A87321B1 FOREIGN KEY (subject_assignment_id) REFERENCES subject_assignment (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6DE30D91A87321B1 ON attendance (subject_assignment_id)');
        $this->addSql('DROP INDEX idx_audit_log_user');
        $this->addSql('DROP INDEX idx_audit_log_entity');
        $this->addSql('DROP INDEX idx_enrollment_grade_section');
        $this->addSql('DROP INDEX idx_enrollment_student_cycle');
        $this->addSql('ALTER TABLE grade ADD sort_order INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_grade_record_teacher');
        $this->addSql('DROP INDEX idx_grade_record_lookup');
        $this->addSql('DROP INDEX idx_payment_student_pending');
        $this->addSql('DROP INDEX idx_payment_status_date');
        $this->addSql('ALTER TABLE payment ADD ip_address VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP billing_identifier');
        $this->addSql('ALTER TABLE payment DROP billing_name');
        $this->addSql('DROP INDEX idx_5a3811fbfbaa2526');
        $this->addSql('DROP INDEX idx_5a3811fb591cc992');
        $this->addSql('ALTER TABLE schedule ADD grade_id INT NOT NULL');
        $this->addSql('ALTER TABLE schedule DROP period');
        $this->addSql('ALTER TABLE schedule DROP is_active');
        $this->addSql('ALTER TABLE schedule DROP course_id');
        $this->addSql('ALTER TABLE schedule ALTER classroom TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE schedule ALTER school_cycle_id DROP NOT NULL');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBFE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBD823E37A FOREIGN KEY (section_id) REFERENCES section (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5A3811FBFE19A1A8 ON schedule (grade_id)');
        $this->addSql('ALTER TABLE staff ADD job_title_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE staff ADD CONSTRAINT FK_426EF3926DD822C6 FOREIGN KEY (job_title_id) REFERENCES job_title (id)');
        $this->addSql('CREATE INDEX IDX_426EF3926DD822C6 ON staff (job_title_id)');
        $this->addSql('DROP INDEX idx_student_active');
        $this->addSql('ALTER TABLE student ALTER version SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE schedule_constraint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, parameters JSON NOT NULL, severity VARCHAR(20) NOT NULL, weight INT NOT NULL, school_cycle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6980f9b0fbaa2526 ON schedule_constraint (school_cycle_id)');
        $this->addSql('CREATE TABLE teacher_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a968568d41807e1d ON teacher_availability (teacher_id)');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91A87321B1');
        $this->addSql('DROP INDEX IDX_6DE30D91A87321B1');
        $this->addSql('ALTER TABLE attendance ADD schedule_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD subject_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD teacher_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD bimester_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attendance DROP subject_assignment_id');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d913f3d70ea FOREIGN KEY (bimester_id) REFERENCES bimester (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d91b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d91a40bc2d5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d9123edc87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT fk_6de30d9141807e1d FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_6de30d91b03a8386 ON attendance (created_by_id)');
        $this->addSql('CREATE INDEX idx_6de30d9141807e1d ON attendance (teacher_id)');
        $this->addSql('CREATE INDEX idx_6de30d9123edc87 ON attendance (subject_id)');
        $this->addSql('CREATE INDEX idx_6de30d91a40bc2d5 ON attendance (schedule_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_student_schedule_date ON attendance (student_id, schedule_id, date)');
        $this->addSql('CREATE INDEX idx_6de30d913f3d70ea ON attendance (bimester_id)');
        $this->addSql('CREATE INDEX idx_audit_log_user ON audit_log (user_id, created_at)');
        $this->addSql('CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id, created_at)');
        $this->addSql('CREATE INDEX idx_enrollment_grade_section ON enrollment (grade_id, section_id)');
        $this->addSql('CREATE INDEX idx_enrollment_student_cycle ON enrollment (student_id, school_cycle_id)');
        $this->addSql('ALTER TABLE grade DROP sort_order');
        $this->addSql('CREATE INDEX idx_grade_record_teacher ON grade_record (entered_by_id, created_at)');
        $this->addSql('CREATE INDEX idx_grade_record_lookup ON grade_record (student_id, bimester_id, subject_assignment_id)');
        $this->addSql('ALTER TABLE payment ADD billing_identifier VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD billing_name VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment DROP ip_address');
        $this->addSql('CREATE INDEX idx_payment_student_pending ON payment (student_id, status) WHERE ((status)::text = \'PENDING\'::text)');
        $this->addSql('CREATE INDEX idx_payment_status_date ON payment (status, due_date)');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB23EDC87');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB41807E1D');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FBFE19A1A8');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FBD823E37A');
        $this->addSql('DROP INDEX IDX_5A3811FBFE19A1A8');
        $this->addSql('ALTER TABLE schedule ADD is_active BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE schedule ADD course_id INT NOT NULL');
        $this->addSql('ALTER TABLE schedule ALTER classroom TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE schedule ALTER school_cycle_id SET NOT NULL');
        $this->addSql('ALTER TABLE schedule RENAME COLUMN grade_id TO period');
        $this->addSql('CREATE INDEX idx_5a3811fbfbaa2526 ON schedule (school_cycle_id)');
        $this->addSql('CREATE INDEX idx_5a3811fb591cc992 ON schedule (course_id)');
        $this->addSql('ALTER TABLE staff DROP CONSTRAINT FK_426EF3926DD822C6');
        $this->addSql('DROP INDEX IDX_426EF3926DD822C6');
        $this->addSql('ALTER TABLE staff DROP job_title_id');
        $this->addSql('ALTER TABLE student ALTER version DROP NOT NULL');
        $this->addSql('CREATE INDEX idx_student_active ON student (is_active) WHERE (is_active = true)');
    }
}
