# Symfony services configuration
parameters:
    corposistemas_api_url: '%env(CORPOSISTEMAS_API_URL)%'
    corposistemas_api_key: '%env(CORPOSISTEMAS_API_KEY)%'
    corposistemas_nit: '%env(CORPOSISTEMAS_NIT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DTO/'

    App\Service\CorpoSistemasService:
        arguments:
            $corposistemasApiUrl: '%corposistemas_api_url%'
            $corposistemasApiKey: '%corposistemas_api_key%'
            $corposistemasNit: '%corposistemas_nit%'

    App\Service\AuthenticationService:
        arguments:
            $secureCookies: false
